### ISSUE TITLE
Make updated qt5 version

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter-deps#17]
* Make a separate qt5 branch for cutter-deps based on last commit before qt6 update
* use latest 5.15 patch version from KDE
* probably update python to 3.11

**Comment by karliss** [comment]
https://invent.kde.org/qt/qt/qt5/-/tree/kde/5.15?ref_type=heads

**Comment by karliss** [comment]
* [x] cutter-deps-qt compiles
* [x] cutter-deps-qt compiles
* [x] cutter compiles
* [x] cutter tested
* [x] PR merged
    - [x] cutter-deps-qt  rizinorg/cutter-deps-qt#8
    - [x] cutter-deps  rizinorg/cutter-deps#19
    - [x] cutter  rizinorg/cutter#3404
